<?php

return [
    [
        'title' => 'Dashboard',
        'route' => 'Pages.dashboard',
        'icon'  => 'fas fa-home',
        'active_check' => 'dashboard*',
        'ability' => null, 
    ],
    [
        'title' => 'Roles Management',
        'route' => 'Pages.roles.index',
        'icon'  => 'fas fa-users-cog',
        'active_check' => 'roles*',
        'ability' => 'viewAny',
        'model' => App\Models\Role::class,
    ],
    [
        'title' => 'Employees',
        'route' => 'Pages.employee.index',
        'icon'  => 'fas fa-users',
        'active_check' => 'employee*',
        'ability' => 'viewAny',
        'model' => App\Models\Employee::class,
    ],
    [
        'title' => 'Food Categories',
        'route' => 'Pages.categories.index',
        'icon'  => 'fas fa-utensils',
        'active_check' => 'categories*',
        'ability' => 'viewAny',
        'model' => App\Models\CategoriesRestaurant::class,
    ],
    [
        'title' => 'Items Menu',
        'route' => 'Pages.Items.index',
        'icon'  => 'fas fa-hamburger',
        'active_check' => 'items*',
        'ability' => 'viewAny',
        'model' => App\Models\ItemsRestaurant::class,
    ],
    [
        'title' => 'Cashier Screen',
        'route' => 'Pages.cashier.index',
        'icon'  => 'fas fa-cash-register',
        'active_check' => 'cashier*',
        'ability' => 'viewAny',
        'model' => App\Models\Cachier::class,
    ],
    [
        'title' => 'Tables Management',
        'route' => 'Pages.Tables.index',
        'icon'  => 'fas fa-table',
        'active_check' => 'tables*',
        'ability' => 'viewAny',
        'model' => App\Models\TablesRestaurant::class,
    ],
    [
        'title' => 'Invoises',
        'route' => 'Pages.invoices.index',
        'icon'  => 'fas fa-receipt',
        'active_check' => 'invoices*',    
        'ability' => 'viewAny',
        'model' => App\Models\OrderItemsRestaurant::class,
    ],
    [
        'title' => 'Kitchen Screen',
        'route' => 'Pages.kitchen.index',
        'icon'  => 'fas fa-concierge-bell',
        'active_check' => 'kitchen*',
        'ability' => 'viewAny',
        'model' => App\Models\Kitchen::class,
    ],
    [
        'title' => 'Waiter Screen',
        'route' => 'Pages.waiter.index',
        'icon'  => 'fas fa-user-tie',
        'active_check' => 'waiter*',
        'ability' => 'viewAny',
        'model' => App\Models\Waiter::class,
    ],
    
    [
        'title' => 'Inventory',
        'route' => 'Pages.inventory.index',
        'icon'  => 'fas fa-warehouse',
        'active_check' => 'inventory*',
        'ability' => 'viewAny',
        'model' => App\Models\Inventory::class,
    ],
    [
        'title' => 'Reports',
        'route' => 'Pages.reports.index',
        'icon'  => 'fas fa-chart-line',
        'active_check' => 'reports*',
        'ability' => 'viewAny',
        'model' => App\Models\Report::class,
    ],
];