<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>

<style>
    .glass-card {
        background: rgba(22, 24, 26, 0.8);
        backdrop-filter: blur(14px);
        border: 1px solid rgba(212, 175, 55, 0.15);
        border-radius: 24px;
        padding: 25px;
    }

    .custom-table thead th {
        background: rgba(212, 175, 55, 0.08);
        color: #f5d76e;
        font-weight: 800;
        border: none;
        padding: 18px;
        font-size: 14px;
        letter-spacing: .5px;
    }

    .custom-table td {
        font-size: 13px;
    }

    #printableReportArea {
        display: none;
        background: white;
        color: black;
        width: 210mm;
        direction: rtl;
        font-family: 'Arial', sans-serif;
    }

    .report-table-official {
        width: 100%;
        border-collapse: collapse;
        table-layout: fixed;
    }

    .report-table-official th {
        background-color: #f8f9fa !important;
        border: 1px solid #000 !important;
        padding: 10px;
        font-size: 14px;
        font-weight: bold;
        color: #000;
        -webkit-print-color-adjust: exact;
    }

    .report-table-official td {
        border: 1px solid #000 !important;
        padding: 8px;
        text-align: center;
        font-size: 12px;
    }

    .report-table-official tr {
        page-break-inside: avoid !important;
    }
 /* .text-date {
    color: #ebebeb !important;          /* أسود واضح */
    font-weight: 600;                /* أوضح */
    font-size: 12px;                 /* مقروء */
    letter-spacing: .3px;
} */


</style>

{{-- ===== HEADER ===== --}}
<div class="d-flex justify-content-between align-items-center mb-4 px-3 d-print-none">
    <h4 class="text-white fw-black mb-0">
        | {{ __('financial operations log') }}
    </h4>

    <button onclick="exportOfficialReport()" class="btn btn-danger rounded-pill px-4 fw-bold shadow-lg">
        <i class="fas fa-file-pdf me-2"></i>
        {{ __('export official report') }}
    </button>
</div>

{{-- ===== TABLE ===== --}}
<div class="glass-card overflow-hidden d-print-none">
    <div class="table-responsive" style="max-height: 550px; overflow-y: auto;">
        <table class="table table-dark custom-table align-middle text-center mb-0">
            <thead>
                <tr>
                    <th>{{ __('invoice number') }}</th>
                    <th>{{ __('service type') }}</th>
                    <th>{{ __('amount paid') }}</th>
                    <th>{{ __('date time') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($invoices as $inv)
                    <tr>
                        <td class="text-white fw-bold font-monospace">
                            #{{ $inv->invoice_number }}
                        </td>
                        <td>
                            {{ $inv->dine_in_order_id ? __('dine in') : __('takeaway') }}
                        </td>
                        <td class="fw-black" style="color:#f5d76e;">
                            {{ number_format($inv->amount_paid, 0) }} {{ __('currency') }}
                        </td>
                        <td class="info-label text-date" style="direction:ltr;">
                            {{ $inv->created_at->format('Y-m-d | H:i') }}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

{{-- ===== PRINTABLE REPORT ===== --}}
<div id="printableReportArea">
    <div style="padding: 10mm 15mm;">

        <div style="text-align:center;border-bottom:4px double #d4af37;padding-bottom:15px;margin-bottom:20px;">
            <h1 style="margin:0;color:#d4af37;font-size:28px;">
                {{ __('restaurant name') }}
            </h1>
            <p style="margin:6px 0;font-size:16px;font-weight:bold;color:#333;">
                {{ __('general invoices report') }}
            </p>
        </div>

        <table style="width:100%;margin-bottom:20px;font-size:13px;">
            <tr>
                <td style="text-align:right;">
                    {{ __('export date') }}:
                    <strong>{{ date('Y-m-d H:i') }}</strong>
                </td>
                <td style="text-align:left;">
                    {{ __('generated by') }}:
                    <strong>{{ auth()->user()->name }}</strong>
                </td>
            </tr>
        </table>

        <table class="report-table-official">
            <thead>
                <tr>
                    <th>{{ __('invoice number') }}</th>
                    <th>{{ __('service type') }}</th>
                    <th>{{ __('amount paid') }}</th>
                    <th>{{ __('date time') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($invoices as $inv)
                    <tr>
                        <td style="direction:ltr;">#{{ $inv->invoice_number }}</td>
                        <td>{{ $inv->dine_in_order_id ? __('dine in service') : __('takeaway order') }}</td>
                        <td style="font-weight:bold;">
                            {{ number_format($inv->amount_paid, 0) }} {{ __('currency') }}
                        </td>
                        <td class="info-label text-date" style="direction:ltr;">
                            {{ $inv->created_at->format('Y-m-d H:i') }}
                        </td>

                    </tr>
                @endforeach
            </tbody>
        </table>

        <div
            style="margin-top:25px;padding:15px;border:2px solid #000;background:#fffdf5;
                    display:flex;justify-content:space-between;align-items:center;">
            <span style="font-size:16px;font-weight:bold;">
                {{ __('total amount') }}
            </span>
            <span style="font-size:20px;font-weight:900;">
                {{ number_format($invoices->sum('amount_paid'), 0) }} {{ __('currency') }}
            </span>
        </div>

        <div
            style="margin-top:35px;text-align:center;font-size:10px;color:#777;border-top:1px solid #eee;padding-top:10px;">
            {{ __('auto generated notice') }}
        </div>

    </div>
</div>

<script>
    function exportOfficialReport() {
        const element = document.getElementById('printableReportArea');
        element.style.display = 'block';

        html2pdf().set({
            margin: [10, 5, 10, 5],
            filename: 'Official_Report_{{ date('Ymd_Hi') }}.pdf',
            image: {
                type: 'jpeg',
                quality: 1
            },
            pagebreak: {
                mode: ['avoid-all', 'css']
            },
            html2canvas: {
                scale: 2,
                backgroundColor: '#ffffff'
            },
            jsPDF: {
                unit: 'mm',
                format: 'a4',
                orientation: 'portrait'
            }
        }).from(element).save().then(() => {
            element.style.display = 'none';
        });
    }
</script>
